### PR TITLE
handle TMS

### PR DESCRIPTION
**Pull request by RonnyTite**
- In case of TMS,  we load a first container_XXX.js which triggers aynchronously the loading of the standard Piwik.js.

this was throwing an error in `initMatomo` when trying to assign window.Piwik
`const Matomo = window.Piwik.getAsyncTracker()`

the catch will follow with another error of `src of target undefined` (following [PR#48](https://github.com/AmazingDreams/vue-matomo/pull/48))
Fix created in [PR#51 ](https://github.com/AmazingDreams/vue-matomo/pull/51)

This will avoid the error throwed in initMatomo when window.Piwik is undefined

### CODE REVIEW

**Comment by AmazingDreams** [comment]
Can you provide some kind of test setup? It looks good, but I'm just wondering how it works with the TMS

**Comment by RonnyTite** [comment]
here : https://developer.matomo.org/guides/tagmanager/embedding

If you're already using matomo you can set you _siteId_, your _trackerUrl_,

and set the TMS script as _trackerFileName_ (`container_<something>.js`) .

It should be testable with this.

**Comment by RonnyTite** [comment]
@AmazingDreams were you able to test ?

**Comment by AmazingDreams** [comment]
Sorry it took me so long, thanks for your contribution

**Pull request merged**
