### PR TITLE
bugfix Uncaught (in promise)

### PR DESCRIPTION
**Pull request by Liuxg0112**

### CODE REVIEW

**Comment by dlecan** [comment]
Is it possible to merge this PR?
It solves ugly error log in browser console

**Comment by dlecan** [comment]
Thank you

**Comment by AmazingDreams** [comment]
Thank you, and sorry for taking so long. v3.13.0-1

**Comment by dlecan** [comment]
@AmazingDreams 
>v3.13.0-1

How long does it take to release a new version?
This version is not available on NPMJS: https://www.npmjs.com/package/vue-matomo

Thank you

**Comment by AmazingDreams** [comment]
Weird, I was pretty sure I published this. But I just published it again.

**Pull request merged**
